_commit: 0.0.2rc-180-g2a2d737
_src_path: gh:bswck/skeleton
author: bswck
cli: true
copyright: Bartosz Sławecki
description: Set up projects for development quickly.
docs: true
email: bartoszpiotrslawecki@gmail.com
github: bswck
license: MIT
package: project
precommit: true
pypi: true
pypi_description: Set up projects for development quickly.
pypi_project: project
pypy: true
python: '3.8'
python_until: '4.0'
repo: project
rtd: project
tests: true
tidelift: false
visibility: public
wip: true
