_commit: 0.0.2rc-219-g781ce0c
_src_path: gh:skeleton-ci/skeleton-python
author: bswck
cli: true
copyright: Bartosz Sławecki
description: Set up projects for development quickly.
docs: true
email: bartoszpiotrslawecki@gmail.com
github: bswck
license: MIT
package: pj
precommit: true
pypi: true
pypi_description: Set up projects for development quickly.
pypi_project: pj
pypy: true
python: '3.8'
python_until: ''
repo: pj
rtd: pj
tests: true
tidelift: false
visibility: public
wip: true
